### ISSUE TITLE
To disable past dates

### ISSUE THREAD

**Issue by Anurag690** [Kunzisoft/Android-SwitchDateTimePicker#11]
How can we disable past days in this??

**Comment by J-Jamet** [comment]
Hi !
You can add code in the project, the problem will be to manage the time lock on the different views and to synchronize them.You must add gray parts to the views, prevent the cursor from each view from going over those gray areas. And manage the listeners so that the time is compatible with the day of the month of the year, that the day is compatible with the month of the year, etc ...
It's a lot of work and if you want to contribute it will be very appreciated. :) For the moment, I add  features of the other posts.

**Comment by arunsekaran02** [comment]
materialCalendarView.state().edit().setMinimumDate(CalendarDay.from(2016, 12, 31)).commit();

https://github.com/prolificinteractive/material-calendarview

**Comment by J-Jamet** [comment]
You're right, there's a bug with the years. The setter is used by style attributes in
```
<com.kunzisoft.switchdatetime.date.widget.ListPickerYearView
            xmlns:year="http://schemas.android.com/apk/res-auto"
            android:id="@+id/yearPicker"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            year:minYear="1900"
            year:maxYear="3000"
            year:defaultYear="2016"
            />
```
And setter can't be changed because of 
```
setMinYear(yearTypedArray.getInt(R.styleable.ListPickerYearView_minYear, minYear));
setMaxYear(yearTypedArray.getInt(R.styleable.ListPickerYearView_maxYear, minYear));
```
I will change the code so that the setters have priority over the XML. I will also change the listView by a recycleView because I have found delays.
I will try to upload the new version in the day.

**Comment by J-Jamet** [comment]
OK, It's working in my PC but I must change few bugs before commit. You will be able to set a minimum and maximum dates but I have not yet manage hours and minutes.

**Comment by arunsekaran02** [comment]
Thank you @J-Jamet

**Comment by J-Jamet** [comment]
You can do this now with 1.4 version, but you can't precise a time for restriction.

**Comment by J-Jamet** [comment]
Link #33
